pipeline:
  build:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - repo=hitko/nginx-pagespeed
    secrets: 
      - username
      - password
    commands:
      - docker info
      - docker login -u $$USERNAME -p $$PASSWORD
      - docker build $$(for v in $$(cat version); do echo "-t $repo:$v"; done) .
      - docker push $$repo
